version: "3"
services:
  # db: 
  #   image: postgres:latest
  #   env_file:
  #     - .env
  #   volumes:
  #     - data:/var/lib/postgresql/data

  api:
    build: 
      context: ./
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    # depends_on:
    #   - db
  

  # nginx: # Reverse proxy, mainly used to access container by service name, v.g. api/
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - db
  #     - api
  #     - app
  #   ports:
  #     - "3456:3456"
# volumes:
#   data:
  