version: "3"
services:
  db: 
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: 
      context: ./
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  data:
  